#![warn(clippy::all)]

pub mod aaak;
pub mod adoption_analytics;
#[cfg(feature = "rest")]
pub mod api;
pub mod bootstrap_events;
pub mod brief;
pub mod context;
pub mod core;
pub mod cowork;
pub mod crystallize;
pub mod daemon;
pub mod daemon_bootstrap;
pub mod daemon_singleton;
#[cfg(target_os = "linux")]
pub(crate) mod db_path_identity;
pub mod doctor;
pub mod embed;
pub mod endpoint_health;
pub mod factcheck;
pub mod field_taxonomy;
pub mod hook;
pub mod hook_install;
pub mod hotpatch;
pub mod importance;
pub mod ingest;
pub mod integrations;
pub mod intelligence;
pub mod knowledge_anchor;
pub mod knowledge_card_backfill;
pub mod knowledge_card_lifecycle;
pub mod knowledge_card_retrieval;
pub mod knowledge_distill;
pub mod knowledge_gate;
pub mod knowledge_lifecycle;
pub mod llm;
pub mod mcp;
pub mod observability;
pub mod process_diagnostics;
pub mod repair;
pub mod search;
pub mod session_review;
pub mod sleep;
pub mod xurl;
